### ISSUE TITLE
Updater

### ISSUE THREAD

**Issue by ghost** [zdimension/SharpBoot#1]
Hello! Please make a updater for SharpBoot or with every new release upload file "SharpBoot.exe". I write a updater (non-intregated, on AutoIt or batch, i don't good on programming). Thanks!

**Comment by zdimension** [comment]
Done!
![image](https://cloud.githubusercontent.com/assets/4533568/11709727/3897e982-9f1a-11e5-96b0-7fe6fc69d4e6.png)
![image](https://cloud.githubusercontent.com/assets/4533568/11709722/2919f2fc-9f1a-11e5-9529-322040b509ac.png)
