### ISSUE TITLE
Qemu is not working from SharpBoot v4.2

### ISSUE THREAD

**Issue by quertest** [zdimension/SharpBoot#10]
I guess it's up to updated 7-Zip version in v4.2 (when unpacking Qemu). When I open the SharpBoot ISO file in Qemu 2.5 installed locally, everything works fine.

**Comment by zdimension** [comment]
Are you getting any DLL missing error or something like that?

**Comment by quertest** [comment]
No, it will only open a black box and closes again immediately. In SharpBoot v4.0 + v4.1 it works.

**Comment by zdimension** [comment]
What happens if you try to boot an USB key with SharpBoot (either build one or drag-n-drop one from Windows Explorer to the qemu try panel in SharpBoot)

**Comment by quertest** [comment]
If I use 'Create multiboot USB key' the following message is displayed when Qemu starts: 'The program can not start because libcairo-2.dll missing on the computer'.

**Comment by zdimension** [comment]
Ok, then it's normal, I forgot to include some required DLL files in the latest QEMU bundle in SharpBoot, it'll be fixed in v4.3.
