### ISSUE TITLE
Value too larghe for define data type - ignoring

### ISSUE THREAD

**Issue by filledk** [zdimension/SharpBoot#11]
hey
im trying to make a windows 10 AIO iso ( i had it suceeded before with sharpboot)
but when ever im trying to do it it says:
"Value too large for define data type. file:\Users\filledk\AppData\Temp\Sharpboot_mxi3zzcj.efp\iso/images/windows.10.64BIT.iso is too large for current mkisoft settings - ignoring"
![file too large](https://cloud.githubusercontent.com/assets/18231184/15774972/8e490196-297f-11e6-8e85-5d2ce0f5e71a.png)

it does not copy the windows10 iso to the sharpboot iso

**Comment by zdimension** [comment]
It's strange, these Cygwin warnings shouldn't be here. Could you try to uninstall Cygwin and try again?

**Comment by memoarfaa** [comment]
file size for windows.10.64BIT.iso over than 4 gigabytes

Cygwin and mkisofs can't record any single file with size over than 4 gigabytes

**Comment by zdimension** [comment]
Are you making an USB key or an ISO file?

**Comment by memoarfaa** [comment]
My previous answer was a response to a question filledk
> hey
>im trying to make a windows 10 AIO iso ( i had it suceeded before with sharpboot)
>but when ever im trying to do it it says:
>"Value too large for define data type. file:\Users\filledk\AppData\Temp\Sharpboot_mxi3zzcj.efp\iso/images/windows.10.64BIT.iso is too large for current mkisoft settings - ignoring"

This problem is due to windows.10.64BIT.iso size > 4 GB
Read here
https://bugzilla.redhat.com/show_bug.cgi?id=456221

>In order to get ISO-9660 support for files > 4 GB, you
>need to specify -iso-level 3 or more. If you specify -udf
>only the UDF part will contain large files

note that xp instaltion did't support udf so  There is one solution can make sharpboot ISOs 
support for files > 4 GB  solution is add "-iso-level 3" paramter to mkisofs
eg
> p.StartInfo.Arguments += " " + bloader.CmdArgs +  " -iso-level 3 -publisher \"SharpBoot\" -no-emul- >boot -boot-load-size 4 -boot-info-table -allow-multidot -allow-lowercase -r -l -D -d -J -joliet-long -b " + bloader.BinFile;
>p.StartInfo.Arguments += " -o \"" + OutputFilepath + "\" \"" + isodir + "\"";

Look at mkisofs parameter here
www.linuxdevcenter.com/cmd/cmd.csp?path=m/mkisofs
Hope this help
