### ISSUE TITLE
Problème de balise et plantage ISO

### ISSUE THREAD

**Issue by Cervoz** [zdimension/SharpBoot#13]
Bonjour,

Lorsque je lance le logiciel, cette erreur apparait plusieurs fois : http://i.imgur.com/oEUe6PY.png
Ensuite, lorsque je clique sur "Ajouter un fichier ISO", il mouline puis plante. Les autres fonctions ne posent pas de problème.

Le souci est connu ?

**Comment by zdimension** [comment]
Oui, j'ai changé le nom de domaine de mon site en raisons de problèmes avec l'hébergeur, et du coup ça casse tout. Je suis actuellement en train de bosser sur un correctif qui devrait sortir dans la soirée.
Je ferai aussi en sorte que le logiciel ne plante plus en cas de nouvelle inaccessibilité du site (d'ailleurs, j'étais quasiment sûr de l'avoir fait, c'est pourquoi je suis assez étonné que ça plante maintenant).

**Comment by Cervoz** [comment]
Ok, merci du retour !

**Comment by zdimension** [comment]
Alors ça a pris un peu plus longtemps que prévu mais du coup ça va être corrigé dans la v5.

**Comment by Cervoz** [comment]
Je salue la conscience professionnelle.

**Comment by zdimension** [comment]
Corrigé dans la [v5.0](https://github.com/zdimension/SharpBoot/releases/tag/v5.0).
