### ISSUE TITLE
Try full grub2 support and fix som bugs

### ISSUE THREAD

**Issue by memoarfaa** [zdimension/SharpBoot#14]
source code here
https://github.com/memoarfaa/SharpBoot/tree/second

**Comment by zdimension** [comment]
Thanks for your edits. The Grub2 ISO creation was already fixed in my local build, but I'm gonna merge your progress printing code into the main repository.

**Comment by memoarfaa** [comment]
with pleasure but you misunderstand the trick at OnDataReceived method

mkisofs OutputDataReceived always null
mkisofs ErrorDataReceived (Get mkisofs output)
both of them is (public event DataReceivedEventHandler)
so i merge them in one method (OnDataReceived )

if you want to delegate method it must be like

  try
                {
                    p.ErrorDataReceived += (sender, args) =>
                    {
                        try
                        {
                            if (args?.Data == null) return;
                            var o = args.Data.Trim();
                            if (!o.Contains('%')) return;
                            
                            var d = Convert.ToDecimal(args.Data.Substring(0, 5));
                            var val = 50 + Convert.ToInt32(Math.Round(d / 2, 0, MidpointRounding.AwayFromZero));
                            ChangeProgress(val, 100, Strings.CreatingISO + "\t" + val.ToString() + "%");
                                
                           

                        }
                        catch
                        {
                            
                        }
                    };
                    p.Start();
                    p.BeginOutputReadLine();
                    p.BeginErrorReadLine(); 
                    while (!p.WaitForExit(1))
                    {
                       System.Threading.Thread.Sleep(50);
                        p.Refresh();
                       Application.DoEvents();
                    }
                }
                catch (FileNotFoundException)
                {
                }
