### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by Mikolaj98p** [zdimension/SharpBoot#15]
The app on startup getting the popup
https://ibb.co/i2mfFa
and going to not responding on adding new ISO and drag'n'drop iso file

**Comment by zdimension** [comment]
I know, my website is down, it's fixed in v5.0 that will be released in 2-3 days.

**Comment by zdimension** [comment]
Okay so v5.0 took a little bit longer than expected. Issue fixed in dev.
