### ISSUE TITLE
Russian Translation

### ISSUE THREAD

**Issue by ghost** [zdimension/SharpBoot#2]
Hello! I'm sorry but I make error in translation, so please renew translation in SharpBoot. Thanks!

**Comment by zdimension** [comment]
Can you tell me what are the changes/modifications you did?

**Comment by ghost** [comment]
I change the word "памьять" to "память"

**Comment by zdimension** [comment]
Fixed 7ef0ef9
Also I added your GitHub page to the credits page 4714d3e
