### ISSUE TITLE
Autodedect Screen Resolution/ selfsfx/burn/write-usbstick/cd = 2 issues

### ISSUE THREAD

**Issue by blackcrack** [zdimension/SharpBoot#6]
Hi,
an autodedect Screen Resolution it's maybe also not bad, 
because it's give different Monitors in different way's
like LED, OLED and so on.. 
so, an possible to use this with an Checkbox, why not ..

and 2.nd : 
an possible for selfwrite header, an buring algorithm for the 
Extract an iso, write an iso to burner, extract and write a bootsector for an usbstick.
= Create an pack.exe (run-able in wine) for mailing or leaving on an ftp/web or something else..

executable like a winimage where extract or write on floppydisk or into an image(there an iso)
or burn directly in WinNT on an DVD-Burner or something.
Therewith it is possible to execute in Wine or in WinNT like Reactos and don't need an extra burner Software or need only an usb-stick or an blank CD/DVD/BR and can create an Multitool-file for burner or usb-stick.

MEGATOOLS-isoimg.iso.exe 4Gig/8Gig how ever ..

---

What do you want:
[_] Extract me on the [C:/xxxxxx/]open] as ISO and add an grub-boot-loader 
__in the first bootsector for booting me self as iso and installer.
[_]Create the whole on USB (Bootable Device)
[_]Burning the whole in CD/DVD (Bootable Device)
[_] Extract a single CD/DVD on any space as iso/img
_[_] ISO 1 ""Partioneer" Software"
_[_] ISO 2 "Reactos rev. 3320"
_[_] ISO 3 "WinNT XXXXX"
_[_] ISO 3 "OpenMandriva 2014.2-586"
_[_] ISO 4 "OpenMandriva 2014.2-x64_86"
_[_] img 5 "bootdisk.img"
_[_] img 6 "dos622.img"
_[_] img 6 "Freedos.img"
[X]Burning single CD/DVD on CD/DVD (Bootable Device)
_[_] ISO 1 ""Partioneer" Software"
_[_] ISO 2 "Reactos rev. 3320"
_[_] ISO 3 "WinNT XXXXX"
_[_] ISO 3 "OpenMandriva 2014.2-586"
_[_] ISO 4 "OpenMandriva 2014.2-x64_86"
._[_] Extract an ISO on [C:/xxxxxx/]open] and add an grub-boot-loader 
____in the first bootsector for booting it self as iso for installing..
__[_] ISO 1 ""Partioneer" Software"
__[_] ISO 2 "Reactos rev. 3320"
__[_] ISO 3 "WinNT XXXXX"
__[X] ISO 3 "OpenMandriva 2014.2-586"
__[_] ISO 4 "OpenMandriva 2014.2-x64_86"

---

with it can build an megaboot, include different versions of MSWinNT
and i guess ... can an great baby become .. if you see what i meant..

best regards
Blacky

**Comment by ghost** [comment]
This issuse is for Syslinux or Grub4DOS, not SharpBoot. The project developer only must add "Auto" selection in the "Resolution" selector.

**Comment by zdimension** [comment]
I don't really understand what you mean by 'Auto' resolution... Do you mean that it should take the resolution of the screen, like 1920x1080 or 1600x900? Then it would be almost impossible because Syslinux only supports (with vesamenu.c32) resolutions up to 1280x1024, I think Grub4DOS does too.

**Comment by blackcrack** [comment]
yes, you can set up 800x600 , on both boot-loader or still take a auto resolution..
by check the hardware possibility and let take the middle way 
(between the maximal resolution and the minimal resolution possibility)  
:)

best regards
blacky

**Comment by zdimension** [comment]
The maximum resolution for Syslinux and Grub4Dos is 1280x1024

**Comment by blackcrack** [comment]
works not 1360x765 or something.. I thought, should work in different resolution today.. or not?..
with the modern vesa driver ? ..

**Comment by zdimension** [comment]
As i said the max res for the _Syslinux VESA driver_ and *Grub4Dos VESA driver" is 1280x1024, if you want more you need to use an other driver (I haven't found one yet)

**Comment by blackcrack** [comment]
:) how ever, Sharpboot is an very pretty done and good Proggy :+1: , thank you for you sharing your programming work :) i like it also as so, this was only suggestions and ideas.. ( and wanted to not nerfe ) :)  

has found that : http://hdt-project.org/wiki/VESA
Video Electronic Standards Association
http://www.vesa.org/
have looked further : http://bantalaydaohomestay.com/dos-driver-for-usb-dvd-drive/
if.. give a 720p and  1080p display driver code, then there .. maybe only asking ..
or there : http://www.chrontel.com/index.php/products/ch7016-hdtv-sdtv-encoder
something it's maybe an interesting theme .. because the whole Monitors where comes and be on the marked .. it's maybe really well if this supported .. 

best regards
Blacky
