### ISSUE TITLE
 Feature to load or configure own or additional 'apps.xml'

### ISSUE THREAD

**Issue by quertest** [zdimension/SharpBoot#7]
That would be a very helpful feature for quick update of more ISO file lists!

**Comment by zdimension** [comment]
I'm currently working on making a page to add entries to the official apps.xml (with moderation, to prevent problems).
But if there's OSes you want me to add right now, tell me, I will add them ^^

**Comment by zdimension** [comment]
Here it is: https://github.com/zdimension/SharpBoot-AppDB
I may replace this by a web page on my website, but currently you can use that.
